### PR TITLE
ensures permissions stay correct on UNIX domain sockets

### LINKED ISSUE #15: Permissions on UNIX domain socket wrong after cluster gets down to 0 workers
Since https://github.com/jfromaniello/master-process/pull/8 the cluster will stay up even if the workers die/exit and it will attempt to replace them. This leads to a new situation whereby all workers in the cluster have exited, temporarily leaving the cluster with no workers.

When binding to a UNIX domain socket, if the workers have taken care to call [`server.close`](https://nodejs.org/api/net.html#net_server_close_callback) then Node will unlink the underlying UNIX domain sockets as described in 'Identifying paths for IPC connections':

> If the UNIX domain socket (that is visible as a file system path) is created and used in conjunction with one of Node.js' API abstractions such as net.createServer(), it will be unlinked as part of server.close()

https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections

When the first worker binds to the socket again, the file will be created but its permissions will not be set to 644 as they are when the master-process cluster is first started. Depending on the umask of the process, this can make the socket inaccessible to any clients wishing to connect.

### PR DESCRIPTION
**Pull request by luuuis**
Ensure that permissions are correct whenever a worker binds to a UNIX domain socket. Fixes #15.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -123,12 +131,15 @@ module.exports.init = function () {
...
-      fs.chmodSync(address.address, '664');
+    debug('cluster is listening on %s', address.port || address.address);
+  }).on('listening', function (worker, address) {
+    if (address.addressType === -1) { // https://nodejs.org/api/cluster.html#cluster_event_listening_1
+      unix_sockets.add(address.address);
+
+      // due to https://github.com/nodejs/node/issues/19729 the underlying path may have
+      // been unlinked after this cluster has started. ensure that the permissions are
+      // correct whenever a new worker has bound to a UNIX socket.
+      ensurePermsAsync(address.address, '664');
```
Comment (ziluvatar) [inline index.js]: I saw you changed Sync => Async, any reason related to the issue?

Comment (luuuis) [reply index.js]: Only because this is now happening "continually" as new workers come up, so I am avoiding blocking the event loop of the master process for I/O.

**Review by ziluvatar — APPROVED** [review]
